# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - karaoke-ws

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: SCP Deployment
        uses: srueda99/scp-action@v12
        with:
          port: 22
          host: 20.42.85.210
          origin: "./release.zip"
          destination: "/home/azureuser/ws-release.zip"
          username: azureuser
          key: ${{ secrets.VMPEMPRIVATEKEY }}

      - name: SSH Command
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
            user: azureuser
            private_key: ${{ secrets.SSH_PRIVATE_KEY }}
            host: 20.42.85.210
            port: 22
            command:
              rm /home/azureuser/ws-app -rf &&
              unzip /home/azureuser/ws-release.zip /home/azureuser/ws-app &&
              cd /home/azureuser/ws-app && yarn start
